### ISSUE TITLE
Stardew Access Compatibility for Stardew Valley 1.6

### ISSUE THREAD

**Issue by fz0308** [stardew-access/stardew-access#200]
From his Twitter, ConcernedApe announced Stardew Valley 1.6 will be release 19th of March. Please update Stardew Access so this accessibility mod will be compatible with Stardew Valley 1.6

**Comment by khanshoaib3** [comment]
@fz0308 We are already on it. We will be releasing a beta soon to test the mod's compatibility with sdv 1.6

**Comment by ParadoxiKat** [comment]
@fz0308 we have been working on it since mid December! We have a very buggy alpha build that compiles and loads but has lots of issues so it's not ready for public release. But this is our highest priority for the next several weeks. I occasionally stream coding sessions as I work on it and test runs as it improves if you'd like to keep up on the progress. :)

**Comment by khanshoaib3** [comment]
Closing this issue as we are actively working and there are a lot related issues now open :)
