### ISSUE TITLE
New Neighbours' Requests Are Inaccessible

### ISSUE THREAD

**Issue by LucieG0** [stardew-access/stardew-access#216]
The 1.6 added an update with a new way to get raccoons as neighbours. This is done by completing a quest to build them a house on top of an old fallen tree. Once you do that, the first raccoon moves in and asks you for items. Stardew-access doesn't read what he's asking for or how you give it to him. But also once you give him the food, his wife then joins and they ask for more items which I assume is also inaccessible. This loop repeats several times.

**Comment by khanshoaib3** [comment]
@LucieG0 Turns out, the game actually uses the same menu used for the community center bundles. So by using C, I and V keys, the raccoon requests menu is already patched.

As for the tree stump, i'll have that dynamically added to the quest category and to the decor category after it has been fixed.

**Comment by LucieG0** [comment]
Thanks :)
