### ISSUE TITLE
Mod says you've eaten an equals stardrop

### ISSUE THREAD

**Issue by BrailleBennett** [stardew-access/stardew-access#240]
When the farmer consumes a stardrop, the dialogue that happens says you ate an equals stardrop. Obviously the equals sign doesn't make sense to be read out for text to speech users and should be suppressed, assumably, this is either used as a mark down attribute internally, and is leaking through, or is visually there to show emphasis on the word stardrop.

**Comment by ParadoxiKat** [comment]
The mod is speaking what the game is showing. The equals signs (there are two) are included for emphasis. Therefore this is not a bug but expected behavior.
This can be resolved on the player's end via screen reader punctuation settings, speech dictionary settings etc if it's bothersome.
As this isn't a special dialog, but a standard dialog, to resolve it on the stardew-access side would require comparing *every* spoken dialog against the stardrop message to filter out the equals signs, or to filter out equals signs from all speech. Neither is an ideal solution.
