### ISSUE TITLE
Donating an artifact by utilizing the C key unlocks all museum rewards

### ISSUE THREAD

**Issue by BrailleBennett** [stardew-access/stardew-access#264]
When you have an artifact to donate to the museum, if you donate with C, the game incorrectly awards the player every single reward. This behavior was not reproducible with the left click pick up and place method, but was 100% reproducible every attempt via the C key method.

**Comment by danielw97** [comment]
At the risk of adding unnecessary noise to the conversation, I've just attempted to reproduce this with SDV 1.6.2 and the latest Stardew Access from the development branch, and can't get this to happen.
Using c to donate works as expected at least for me on windows.
Edit: nvm, please disregard my last as this has already been fixed in the version I'm running.

**Comment by khanshoaib3** [comment]
Fixed in #256
