### ISSUE TITLE
tile movement in build menu very inconsistant

### ISSUE THREAD

**Issue by lilmike** [stardew-access/stardew-access#309]
I'm playing on the new meadowlands farm, and when I move with left right up or down arrows in the build menu at robin's, at first it moves by one tile, but pretty quickly it starts jumping by 8, then 16, and then it just seems to jump to some random tile. Even worse, if I move right enough for the x coordinate to be correct for where I want to be, and then start moving up or down, the x coordinate will keep increasing f or several presses. As a side note, it would be nice if someone could fix chhat commands, since that's the only non-buggy way to build currently, but it doesn't support 1.6.

-Michael.

**Comment by ParadoxiKat** [comment]
This isn't a bug; this is how the menu actually works. Let me explain:
For sighted players, a viewport is opened on the farm. It does not show the player; it is just a window of a section of your farm. You can move the mouse cursor around this static window of a part of your farm, and click on any free tile to try and build there.
This viewing area is about 20 to 25 tiles wide (not exact). So it's highly likely it's not showing you the spot you want, and you will have to scroll it in some direction. This is achieved by moving the mouse cursor to the edges of the window. If you move the mouse to the left edge, it immediately starts scrolling the farm map left. Top of the window to go up, etc.
When you first open the build menu, stardew-access centers the mouse cursor on the screen, thus centering it in the viewport window of the farm.
When you arrow, it is directly moving the mouse cursor itself left, right, up, down, by the width of a tile and reading that tile.
I don't know meadowland farm coordinates off the top of my head, but on the standard farm it usually starts you around the farm house door, at (64, 14).
If you start pressing left arrow, you will get to around x=50 as expected, moving one tile at a time.
If you move left more to 49 or 48 however, the mouse cursor has reached the far left edge of the physical screen; there is no more visible map to the left. It would be impossible to move it left passed the screen pixel x = 0. This is when the game itself, operating as intended begins scrolling the map itself under the viewing window. The mouse cursor stays in place at the far left of your screen, but the map itself begins scrolling left -- changing the tile under your cursor rather than moving your cursor.
If you move right again, moving the cursor away from the left edge the scrolling stops. You can then arrow right 20 to 25 tiles before it starts scrolling rapidly to the right again. This is the same for up/down, nearing the top or bottom of the screen.

While this is in fact expected behavior and not a bug, it's not communicated well to the blind player at the moment. I attempted to get it to speak when it was scrolling, but could not find any way to detect that scrolling had actually stopped. This was causing the messages to be spoken once and then not again. I still plan to do more work trying to get that figured out -- and additionally I want to add a sound effect to indicate that it's scrolling.

That said, it had been nearly two weeks since a release -- this does work as intended if properly explained, and I'd had less than 6 hours of sleep in two days. I opted for releasing it over getting it well polished for beta3. I'd say expect the announcements and/or scrolling sound in beta4. Both if possible, at least one of them for sure.

As to chat commands, that mod is not made by us and you'd need to take it to that author's github for getting it updated. Given that the internal parts of smapi it used to do it's thing were deprecated before smapi 4.0, and removed in smapi 4.0, I suspect it won't be updated.

However, you can use the command `debug togglecheats` in the console window once to enable debug commands in the game without a chat commands mod. You do that once in the console, then for the rest of your session in game chat debug commands will work.
Also, in this release a config option was added to stardew-access to have it do this automatically for you, so you don't have to type that command each time. Look for the `EnableCheats` config option. Set it to true. `Debug warp` to your heart's content.

**Comment by lilmike** [comment]
So what I was more hoping for in chat commands is the mark and marklist
and build andbuildlist commands. If those are not part of chat commands
feel free to correct me, but under my current mod list those commands
don't seem to exist.

-Michael.



-- 
Sorry about the test, it's just a me thing.
Michael Taboada, Creator of Games. Does that make me a god, well, sorta.
My pgp key: 79BC390E8864CD71305D4DD606CD2197A6EE5ED7
My website: https://michaels.world
2MB website: https://2mb.games
Don't believe everything you read on the internet. I might not be real, you might not be real, and this email certainly isn't real.
Sent from my bedside...
stationary bicycle

**Comment by khanshoaib3** [comment]
How about having a sub menu open up as a replacement for `buildlist` and `marklist`?

**Comment by khanshoaib3** [comment]
The commands now work from chat and we don't need any extra mod :)
Although, there is a small caveat, when using buildlist or marklist, it will send the message of the list as a single message.
So it will read all the indexes at once.
Let me know if ya'll think this should be reverted to how chat commands used to handle it.

**Comment by ParadoxiKat** [comment]
I think using console commands is a sometimes necessary *work around* that is good to have -- but I don't think it's a true solution. Stardew Valley is not a text adventure game or a MUD; players shouldn't need to use / rely on console commands to fully experience the game. As a temporary work around, as a last resort when no other way is possible -- absolutely!
But I fundamentally disagree with the premise that a console command is a close-the-issue worthy solution.
This is a game with a UI that works in a particular way. The goal should be to allow us -- the blind players -- to access it in as nearly as possible to the way the UI was designed.

Again stressing that I think it's great that the console commands work again from chat. But actually using the menu should continue being worked on / improved and ideally the preferred, intuitive to the user and their sighted friends method.

I have some outstanding commits working on this; I will clean it up and finish some testing and hopefully have some more testing done in the coming days.
