### ISSUE TITLE
A problem with the numbpad nav mode addon.

### ISSUE THREAD

**Issue by audiogamer22** [stardew-access/stardew-access#409]
I'm trying to use this mod and so far most things are working fine.

The issue is that I'm unable to use the page up and page down keys, I don't have a set of these on my laptop so have to use the numbpad navigator addon and I think that's what's making the keys not work correctly.

Also, your config file is misssing in the config part of the guide so i have no idea how to change the keybindings.

One more thing, I swear I read that the saved favorites accessed by pressing alt and the number keys had favorites mapped to them at the start of a game? All the favorites seam to be clear, I am sleepy so could have miss heard but I'm quite confident I didn't.

Is something wrong there?

**Comment by audiogamer22** [comment]
I've removed the game and will be getting a refund but hope you see this and can try it with the addon to see if it can be fixed, or to map some other keys just in case someone else tries this game with that addon.

**Comment by PepperTheVixen** [comment]
I can reproduce your issue using [Numpad Nav Mode](https://addons.nvda-project.org/addons/numpadNavMode.en.html#:~:text=Go%20to%20NVDA's%20preferences%2C%20then,hear%20%22Numpad%20Nav%20Mode%22.). In this case, I would recommend remapping keybindings as needed to work around this since the issue only presents itself with that addon or getting an external keyboard to avoid remapping keys.

The config file is not generated until Stardew Access runs successfully at least once. [This is normal documented behavior](https://github.com/khanshoaib3/stardew-access/blob/development/docs/config.md). Once it's generated, you may remap keys according to the [SMAPI keybinding names](https://stardewvalleywiki.com/Modding:Player_Guide/Key_Bindings).

Favorites are not set by default. You may set them manually per save. [Here's the guide on favorites](https://github.com/khanshoaib3/stardew-access/blob/development/docs/guides/stardew-access-guides.md#object-tracker-favorites).

**Comment by audiogamer22** [comment]
Thanks, i'll close the ticket.

I no longer have the game so will close the ticket and mark it as complete.
