### ISSUE TITLE
Put animals with products to give in pending

### ISSUE THREAD

**Issue by BrailleBennett** [stardew-access/stardew-access#414]
Put animals that can be pet or have a product ready in the pending category please. You could also prefix their names with harvestable or pettable as well. Also, truffles should be moved from the "other" category to the pending category as well.

**Comment by LucieG0** [comment]
Surely things like truffles should just go in the ready category? If they are being moved anywhere? Because you don't have to perform a task on them, you just pick them up right? And things that are just ready to be picked up usually go in the ready category. But I guess it also makes sense to have them in the other category, because they are kind of like foraging, and that's where all the foraging stuff goes. Agree with petable animals being put in the pending category though, because you have to go and interact with them, perform a task, petting them, so they are pending. 
This is just my thoughts anyway, I might be wrong.

**Comment by BrailleBennett** [comment]
Yeah truffles, eggs, duck  feathers, and rabbits feet make sense to be in the ready category. I think that animals with products ready should be pending though, because you have to milk/sheer them to get the product, which is an action.

**Comment by LucieG0** [comment]
Agreed. :)
